version: "3"

services:

  db-broker:
    image: mariadb:latest
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: r00tP@ss!
      MYSQL_DATABASE: broker
      MYSQL_USER: broker
      MYSQL_PASSWORD: broker

  broker:
    image: silintl/idp-id-broker:develop
    ports:
      - "51040:80"
    depends_on:
      - db-broker
    env_file:
      - broker/local.env
    environment:
      API_ACCESS_KEYS: abc123abc123
      APP_ENV: test
      IDP_NAME: development
      EMAIL_SERVICE_accessToken: abc123
      EMAIL_SERVICE_assertValidIp: "false"
      EMAIL_SERVICE_baseUrl: http://email
      MYSQL_DATABASE: broker
      MYSQL_HOST: db-broker
      MYSQL_USER: broker
      MYSQL_PASSWORD: broker
      NOTIFICATION_EMAIL: "dummy@example.com"
      EMAIL_SIGNATURE: (email signature goes here)
      HELP_CENTER_URL: http://helpcenter.example.com
      PASSWORD_PROFILE_URL: http://localhost:51052/#
      SUPPORT_EMAIL: support@example.com
    command: whenavail db-broker 3306 100 /data/run.sh

  phpmyadmin-broker:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "51041:80"
    depends_on:
      - db-broker
    environment:
      PMA_HOST: db-broker
      PMA_USER: broker
      PMA_PASSWORD: broker

  db-ssp:
    image: mariadb:10
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: r00tP@ss!
      MYSQL_DATABASE: ssp
      MYSQL_USER: ssp
      MYSQL_PASSWORD: ssp

  ssp:
    image: silintl/ssp-base:develop
    ports:
      - "80:80"
    depends_on:
      - broker
      - db-ssp
    environment:
      ADMIN_EMAIL: "john_doe@there.com"
      ADMIN_PASS: "a"
      SECRET_SALT: "sortalongrandomstring"
      SECURE_COOKIE: "false"
      SHOW_SAML_ERRORS: "true"
      THEME_COLOR_SCHEME: "orange-light_blue"
      BASE_URL_PATH: http://ssp.local/
      ID_BROKER_ACCESS_TOKEN: abc123abc123
      ID_BROKER_BASE_URI: http://broker
      ID_BROKER_ASSERT_VALID_IP: "false"
      ID_BROKER_TRUSTED_IP_RANGES: 192.168.29.0/24
      IDP_DOMAIN_NAME: ssp.local
      MYSQL_HOST: db-ssp
      MYSQL_DATABASE: ssp
      MYSQL_USER: ssp
      MYSQL_PASSWORD: ssp
      RECAPTCHA_SITE_KEY: asdf
      RECAPTCHA_SECRET: adff
      PASSWORD_CHANGE_URL: http://localhost:51052/#/password/create
      PASSWORD_FORGOT_URL: http://localhost:51052/#/password/forgot
      MFA_LEARN_MORE_URL: http://www.google.com/search?q=2fa
      MFA_SETUP_URL: http://localhost:51052/#/2sv/intro
      PROFILE_URL: http://localhost:51052/#/
      REMEMBER_ME_SECRET: not-a-secret-570c5b18dacd45bd
    volumes:
      - ./ssp/cert:/data/vendor/simplesamlphp/simplesamlphp/cert
      - ./ssp/config/authsources.php:/data/vendor/simplesamlphp/simplesamlphp/config/authsources.php
      - ./ssp/metadata/saml20-idp-hosted.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-hosted.php
      - ./ssp/metadata/saml20-sp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-sp-remote.php
    command: whenavail db-ssp 3306 100 /data/run-idp.sh

  phpmyadmin-ssp:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "51061:80"
    depends_on:
      - db-ssp
    environment:
      PMA_HOST: db-ssp
      PMA_USER: ssp
      PMA_PASSWORD: ssp

  db-pw:
    image: mariadb:latest
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: r00tP@ss!
      MYSQL_DATABASE: pw-api
      MYSQL_USER: pw-api
      MYSQL_PASSWORD: pw-api

  pw-api:
    image: silintl/idp-pw-api:develop
    ports:
      - "51050:80"
    depends_on:
      - db-pw
      - zxcvbn
    volumes:
      - ./pw-api/config.php:/data/common/config/local.php
    env_file:
      - pw-api/local.env
    environment:
      MYSQL_HOST: db-pw
      MYSQL_DATABASE: pw-api
      MYSQL_USER: pw-api
      MYSQL_PASSWORD: pw-api
      IDP_NAME: development
      COMPOSER_ALLOW_SUPERUSER: 1
      COMPOSER_CACHE_DIR: /composer
      ALERTS_EMAIL_ENABLED: "false"
      EMAIL_SERVICE_accessToken: abc123
      EMAIL_SERVICE_assertValidIp: "false"
      EMAIL_SERVICE_baseUrl: http://email
      ADMIN_EMAIL: admin@domain.com
      EMAIL_SIGNATURE: Your friendly Help Desk team
      FRONT_COOKIE_SECURE: "false"
      RECAPTCHA_REQUIRED: "false"
      RECAPTCHA_SITE_KEY:
      RECAPTCHA_SECRET_KEY:
      UI_URL: http://localhost:51052/#
      UI_CORS_ORIGIN: http://localhost:51052
      HELP_CENTER_URL: https://google.com/
      SUPPORT_PHONE:
      SUPPORT_EMAIL: helpdesk@example.org
      SUPPORT_NAME: Help Desk
      SUPPORT_URL:
      SUPPORT_FEEDBACK:
      ZXCVBN_API_BASEURL: http://zxcvbn:3000
      ACCESS_TOKEN_HASH_KEY: nice long random string here
      ALERTS_EMAIL: admin@domain.com
      AUTH_SAML_signRequest: "false"
      AUTH_SAML_checkResponseSigning: "false"
      AUTH_SAML_requireEncryptedAssertion: "false"
      AUTH_SAML_entityId: pw-api.local:51050
      AUTH_SAML_ssoUrl: http://ssp.local/saml2/idp/SSOService.php
      AUTH_SAML_sloUrl: http://ssp.local/saml2/idp/SingleLogoutService.php
      APP_ENV: dev # use real components for emailer, auth, and passwordStore
#      APP_ENV: test # use fake components for emailer, auth, and passwordStore
      ID_BROKER_baseUrl: http://broker
      ID_BROKER_accessToken: abc123abc123
      ID_BROKER_assertValidBrokerIp: "false"

  phpmyadmin-pw:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "51051:80"
    depends_on:
      - db-pw
    environment:
      PMA_HOST: db-pw
      PMA_USER: pw-api
      PMA_PASSWORD: pw-api

  zxcvbn:
    image: wcjr/zxcvbn-api:1.1.0
    ports:
        - "3000"

  pw-ui:
    image: silintl/idp-profile-ui:develop
    command: npm run env -- vue-cli-service serve --host=0.0.0.0 --disable-host-check
    ports:
      - "51052:8000"
    depends_on:
      - pw-api
    env_file:
      - pw-ui/local.env
    environment:
      VUE_APP_API_BASE_URL: http://pw-api.local:51050
      VUE_APP_PRIMARY_COLOR: "#015d99"
      VUE_APP_SECONDARY_COLOR: "#791f5e"


  sync:
    image: silintl/idp-id-sync:develop
    ports:
      - "51070:80"
    depends_on:
      - broker
    volumes:
      - ./sync/google-auth.json:/data/google-auth.json
    env_file:
      - sync/local.env
    environment:
      APP_ENV: dev
      ID_BROKER_CONFIG_accessToken: abc123abc123
      ID_BROKER_CONFIG_baseUrl: http://broker
      ID_BROKER_CONFIG_assertValidIp: "false"
      ID_BROKER_ADAPTER: idp
      ID_STORE_ADAPTER: googlesheets
      ID_SYNC_ACCESS_TOKENS: abc123abc123
      IDP_NAME: development
      EMAIL_SERVICE_accessToken: abc123
      EMAIL_SERVICE_assertValidIp: "false"
      EMAIL_SERVICE_baseUrl: http://email
      EMAIL_SERVICE_validIpRanges: 127.0.0.1
      ALLOW_EMPTY_EMAIL: "true"

  email:
    image: silintl/email-service:develop
    ports:
      - "51030:80"
    depends_on:
      - db-email
      - emailcron
    env_file:
      - email/local.env
    environment:
      APP_ENV: dev
      API_ACCESS_KEYS: abc123
      APP_NAME: email-service
      FROM_EMAIL: "dummy@example.com"
      NOTIFICATION_EMAIL: "dummy@example.com"
      MYSQL_ROOT_PASSWORD: not-a-secret
      MYSQL_HOST: db-email
      MYSQL_DATABASE: email
      MYSQL_USER: email
      MYSQL_PASSWORD: email

  emailcron:
    image: silintl/email-service:develop
    depends_on:
      - db-email
    environment:
      API_ACCESS_KEYS: abc123
      APP_ENV: dev
      APP_NAME: email-service
      FROM_EMAIL: "dummy@example.com"
      NOTIFICATION_EMAIL: "dummy@example.com"
      MYSQL_ROOT_PASSWORD: not-a-secret
      MYSQL_HOST: db-email
      MYSQL_DATABASE: email
      MYSQL_USER: email
      MYSQL_PASSWORD: email
    env_file:
      - email/local.env
    command: /data/run-cron.sh

  db-email:
    image: mariadb:latest
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: r00tP@ss!
      MYSQL_DATABASE: email
      MYSQL_USER: email
      MYSQL_PASSWORD: email

  phpmyadmin-email:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "51031:80"
    depends_on:
      - db-email
    environment:
      PMA_HOST: db-email
      PMA_USER: email
      PMA_PASSWORD: email
